// export * from './icons'
export * from './icons/arrows'
export * from './icons/brand'
export * from './icons/building'
export * from './icons/currency'
export * from './icons/graph'
export * from './icons/hand'
export * from './icons/mail'
export * from './icons/technology'
export * from './icons/typography'
export * from './icons/vowel'
export * from './icons/weather'
export * from './icons/science'
export * from './icons/food'
export * from './icons/navigation'
export * from './icons/media'
export * from './icons/action'
export * from './icons/transportation'
export * from './icons/sport'
export * from './icons/social'
export * from './icons/number'
export type { Rotation, SvgType, SvgWithDirection } from './type'
